name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: x64
      - name: "Get pip cache dir"
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - uses: "actions/cache@v2"
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Install"
        run: |
          python -VV
          python -m pip install -U pip setuptools wheel
          python -m pip install pylint pytest pytest-socket --editable .
          python -m pip freeze --all
      - name: "Analyze code with pylint"
        run: |
          python -m pylint --fail-under=7.5 aoc_dan
      - name: "Run tests for ${{ matrix.python-version }} on ${{ matrix.os }}"
        run: python -m pytest -v --durations=10 --disable-socket
